myfridge/fridge/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<ingredients>[0-9,]+)/$', views.search, name='search'),
    url(r'^best/(?P<ingredients>[0-9,]+)/$', views.search_best, name='search_best'),
    url(r'^recipy/(?P<recipy_id>[0-9]+)/$', views.recipy, name='recipy'),
]

myfridge/jokes/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<id>\d+)/$', views.show_joke, name='show_joke'),
]

myfridge/myfridge/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('fridge.urls')),
    url(r'^jokes/', include('jokes.urls')),

    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

myfridge/football/models.py
from django.db import models

# Create your models here.

myfridge/fridge/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Recipy(models.Model):
    name = models.CharField(max_length=200)
    text = models.TextField()

    def __str__(self):
        return self.name


class Comment(models.Model):
    text = models.TextField()
    publish_date = models.DateTimeField(auto_now_add=True, editable=False)
    author = models.ForeignKey('auth.User')
    recipy = models.ForeignKey(Recipy)
    likes_count = models.IntegerField()


class Ingredient(models.Model):
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
    recipy = models.ForeignKey(Recipy, on_delete=models.CASCADE)
    amount = models.FloatField()

    def __str__(self):
        return self.product.name + ' -> ' + self.recipy.name

myfridge/jokes/models.py
from django.db import models

# Create your models here.

class Joke(models.Model):
    text = models.TextField()
    author = models.ForeignKey('auth.User')
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return 'Анекдот №' + str(self.id) + ' ' + self.text

myfridge/football/views.py
from django.shortcuts import render

# Create your views here.

myfridge/fridge/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.core.exceptions import ObjectDoesNotExist


from .models import Recipy, Product, Comment

def index(request):
    recipys = Recipy.objects.all()

    return render(request, 'fridge/index.html', {
        'recipys': recipys,
        'user': request.user,
    })

def products_by_ingredients(ingredients):
    ingredients = set(map(int, ingredients.split(',')))
    products = Product.objects.filter(pk__in=ingredients)
    for p in products:
        p.search_without = ','.join(str(i) for i in (ingredients - set([p.id])))

    more_products = Product.objects.exclude(pk__in=ingredients)
    for p in more_products:
        p.search_with = ','.join(str(i) for i in (ingredients | set([p.id])))
    return products, more_products, ingredients

def search(request, ingredients): 
    products, more_products, ingredients = products_by_ingredients(ingredients)

    recipys = Recipy.objects.raw('''
        select * from fridge_recipy where id not in (
            select recipy_id from fridge_ingredient
            where fridge_ingredient.product_id not in (%s)
        );
    ''' % ','.join(str(i) for i in ingredients));
    return render(request, 'fridge/index.html', {
        'products': products,
        'more_products': more_products,
        'recipys': recipys,
    })

def search_best(request, ingredients): 
    products, ingredients = products_by_ingredients(ingredients)

    recipys = Recipy.objects.raw('''
        select * from fridge_recipy where id not in (
            select recipy_id from fridge_ingredient
            where fridge_ingredient.product_id not in (%s)
        );
    ''' % ','.join(str(i) for i in ingredients));
    return render(request, 'fridge/index.html', {
        'products': products,
        'more_products': more_products,
        'recipys': recipys,
    })


def recipy(request, recipy_id): 
    recipy = get_object_or_404(Recipy, pk=recipy_id)

    if request.method == 'POST':
        text = request.POST['comment_text']
        user = request.user

        comment = Comment(author = user, text = text, recipy = recipy)
        comment.save()

    return render(request, 'fridge/recipy.html', {
        'recipy': recipy
    })

myfridge/jokes/views.py
from django.shortcuts import render

from .models import Joke

import markdown
import bleach

def index(request):
    return render(request, 'jokes/index.html', {
        "jokes": Joke.objects.all(),
        "user": request.user,
    })

def show_joke(request, id):
    joke = Joke.objects.get(id=id)
    text = bleach.clean(
        markdown.markdown(joke.text),
        tags=['h1', 'h2', 'strong', 'blockquote', 'p'],
    )
    print('Text:', text)
    return render(request, 'jokes/joke.html', dict(
        id=joke.id,
        text=text,
        author=joke.author.username
    ))

myfridge/fridge/templates/fridge/index.html
{% if user %}
Hello, {{ user.username }}!
{% else %}
<a href="/login">Login</a>
{% endif %}
{% if products %}
    <p>
    Показую рецепти які можна зробити з наступних продуктів:
    {% for product in products %}
    {{ product.name }} <a href="/{{product.search_without}}/">[x]</a>{% if not forloop.last %},{% endif %}
    {% endfor %}
    </p>
    <p>
    Може є ще
    {% for product in more_products %}
        {% if forloop.last %} або {% endif %}
        <a href="/{{product.search_with}}/">{{ product.name }}</a>{% if not forloop.last %},{% endif %}
    {% endfor %}?
    </p>
    <hr />
{% endif %}

{% if recipys %}
    <ul>
    {% for recipy in recipys %}
        <li><a href="/recipy/{{ recipy.id }}/">{{ recipy.name }}</a>:
            {% for ing in recipy.ingredient_set.all %} 
                <a href="/{{ing.product.id}}/">{{ ing.product.name }}</a>{% if not forloop.last %},{% endif %}
            {% endfor %} 
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>Рецептів не знайдено :(</p>
{% endif %}

myfridge/fridge/templates/fridge/recipy.html
<h1>{{ recipy.name }}</h1>

<ul>
    {% for ing in recipy.ingredients_set.all %}
        <li>{{ ing.product.name }}: {{ ing.amount }}</li>
    {% endfor %}
</ul>

<p>{{ recipy.text }}</p>

<hr >


{% for comment in recipy.comment_set.all %}
<p><strong>{{comment.author.username}}</strong> {{ comment.text }}</p>
{% endfor %}


<form action="/recipy/{{recipy.id}}/" method="post">
    {% csrf_token %}
    <textarea name="comment_text"></textarea>
    <input type="submit" value="OK">
</form>

myfridge/jokes/templates/jokes/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Анекдоти</title>
    </head>
<body>
    {% if user.is_authenticated %}
        <p> Hello, {{ user.username }} <a href="/admin/logout/">Logout</a></p>
    {% else %}
        <a href="/admin/">Login</a>
    {% endif %}
    {% for joke in jokes %}

    <p><strong>№{{forloop.counter}}</strong>  {{joke.text}}</p>
    {% endfor %}
</body>
</html>

myfridge/jokes/templates/jokes/joke.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Анекдот №{{id}}</title>
        <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'style.css' %}"
        />
    </head>
<body>
    <p>{{text | safe }}
        <hr />
        <i>{{author}}</i>
    </p>
</body>
</html>